export class Request {
    
    constructor(
        public requestid:string,
        public requestcode:string,
        public requesttype:string,
        public category:string,
        public status:string,
        public created_date:string,
        public creater:number,
        public requestor:number,
        public serviceCenter:string =null,    
        public rc1:string           =null,
        public rc1StationId:number,
        public rc1Switching:number  =null,
        public rc2:string           =null,
        public rc2StationId:number  =null,
        public rc2Switching:number  =null,       
        public location:string,
        public bndryClearanceInd:number,
        public clearFeederSection:number=null,
        public clearanceNeededInd:number,
        public feederSwitchingOnly:number,
        public includesCommonEquipment:number,
        public jurisdictionClearanceInd:number,
        public scheduledEndTime:string,
        public scheduledStartTime:string,
        public clearUpTime:string,
        public daily:number,
        public rushInd:number,
        public rushRequestComments:string="",
        public late:number          =null,
        public longterm:number      =null,
        public pastDue:number       =null,
        public stationPermitNeeded:number,
        public switchingRequestOnly:number,
        public testClearance:number,
        public outageScheduleMasterOpf:number,
        public backfeedOnFeeder:number=null,
        public constructionClearance:number,
        public referenceDrawingInt:string,
        public substationOrTransmissionDep:number,
        
        public createdby:string,
        public createddate:string,
        public updatedby:string,
        public updateddate:string 
       ){}
}
